name: CI

on:
  push:
    branches:
      - main
      - test-ci-workflow
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Set up dependencies
      run: sudo apt-get install -y cmake g++ libsdl2-dev libpthread-stubs0-dev

    - name: Download Doom shareware WAD
      run: wget -O shareware_doom_iwad.zip http://www.doomworld.com/3ddownloads/ports/shareware_doom_iwad.zip

    - name: Extract Doom shareware WAD
      run: unzip shareware_doom_iwad.zip -d .

    - name: Move WAD files to correct directory
      run: mv DOOM1.WAD DoomGame/

    - name: Set WAD_PATH environment variable
      run: echo "WAD_PATH=$GITHUB_WORKSPACE/DoomGame" >> $GITHUB_ENV


    - name: Build project
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
      env:
        WAD_PATH: ${{ env.WAD_PATH }}